#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CONFIG_MBASE 0x80000000
#define CONFIG_MSIZE 0x8000000
#define CONFIG_PC_RESET_OFFSET 0x0
#define CONFIG_ITRACE y
#define CONFIG_DIFFTEST y
#define CONFIG_DIFFTEST_REF_NEMU y
#define CONFIG_DEVICE y

#endif
